# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "Milvus : The Definitive Guide"
author: Charles Xie
logo: milvus-logo.png
copyright: "2025 Charles Xie. All rights reserved"
exclude_patterns: ["README.md"]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: milvus-the-definitive-guide.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/cxie/Milvus-The-Definitive-Guide  # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  baseurl: https://cxie.github.io/Milvus-The-Definitive-Guide
  extra_footer: "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License."
